<?php

namespace AppBundle\Repository;

/**
 * ApprovisionnerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApprovisionnerRepository extends \Doctrine\ORM\EntityRepository
{
}
