<?php

namespace AppBundle\Repository;

/**
 * ArreteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArreteRepository extends \Doctrine\ORM\EntityRepository
{
}
